export const stringEn = {
  strName: "Name",
  strLogo: "Logo",
  strLeague: "League",
  strLeagues: "Leagues",
  strLocation: "Location",
  strCountry: "Country",
  strSport: "Sport",
  strAddress: "Address",
  strTime: "Time",
  strHome: "Home",
  strAway: "Away",
  strAll: "All",
  strFinished: "Finished",
  strNotFinished: "Not Finished",
  strOrderBy: "Order by:",
  strMatch: "Matches",
  strAsc: "Ascending order",
  strShowDeleted: "Show deleted",
  strScore: "2Score",
  strAdd: "Add",
  strSearch: "Search:",
  strSearchWithoutSemicolon: "Search",
  strFirstName: "First Name",
  strLastName: "Last Name",
  strImage: "Image",
  strBirthDate: "Birth Date",
  strClub: "Club",
  strClubs: "Clubs",
  strNationality: "Nationality",
  strLogin: "Login",
  strUserName: "Username",
  strPassword: "Password",
  strWrongInput: "Wrong username or password",
  strCreateProfile: "Create new profile",
  strWrongPassword: "Password doesn't match",
  strSuccessfulyRegistration: "Successful registration",
  strError: "An error occurred",
  strWrongEmail: "Email is not valid",
  strAlreadyInUseEmail: "This email is already in use",
  strRequired: "Required",
  strAlreadyInUseUserName: "This username is already in use",
  strValidPaswword: "Valid password",
  strPasswordLenght: "Password must be at least 6 characters long",
  strConfirmPassword: "Confirm password",
  strRepeatedPasswordNotValid: "Repeated password is not valid",
  strRegister: "Register",
  strComment: "Comment",
  strAddComment: "Add comment",
  strCancel: "Cancel",
  strConfirm: "Confirm",
  strScoreHome: "Home score",
  strScoreAway: "Away score",
  strCommentDeleteConfirmation: "Are you sure you want to delete the comment?",
  strDeleteConfirmation: "Are you sure you want to ",
  strYes: "Yes",
  strNo: "No",
  strEdit: "Edit",
  strLogout: "Logout",
  strRowsPerPage: "Rows per page",
  strDeleting: "delete",
  strReturning: "return",
  strDelete: "Delete",
  strReturn: "Return",
  strSomethingWentWrong: "Something went wrong",
  strSuccessfulyCreated: "Successfully created!",
  strSuccessfulyUpdated: "Successfully updated!",
  strSuccessfulyDeleted: "Successfully deleted!",
  strAlreadyTaken: " is already taken.",
  strPlayer: "Player",
  strPlayers: "Players",
  strChange: "Edit",
  strScores: "Scores",
  strSchedule: "Schedule",
  strFavourites: "Favourites",
  strBack: "Back",
  strNoResults: "No results",
  strNoClubs: "No clubs found",
  strNoLeagues: "No leagues found",
  strSearchPlaceholder: "Please type in the requested term.",
  strSearchClubsAndLeagues: "Search for clubs and leagues",
  strErrorBirthDate: "Birth date is not valid",
};

export const stringHr = {
  strName: "Naziv",
  strLogo: "Logo",
  strLeague: "Liga",
  strLeagues: "Lige",
  strLocation: "Lokacija",
  strCountry: "Država",
  strSport: "Sport",
  strAddress: "Adresa",
  strTime: "Vrijeme",
  strHome: "Domaćin",
  strAway: "Gost",
  strAll: "Sve",
  strFinished: "Završene",
  strNotFinished: "Nisu Završene",
  strOrderBy: "Poredaj po:",
  strMatch: "Utakmice",
  strAsc: "Rastući redoslijed",
  strShowDeleted: "Prikaži izbrisane",
  strScore: "2Rezultat",
  strAdd: "Dodaj",
  strSearch: "Pretraži:",
  strSearchWithoutSemicolon: "Pretraži",
  strFirstName: "Ime",
  strLastName: "Prezime",
  strImage: "Slika",
  strBirthDate: "Datum rođenja",
  strClub: "Klub",
  strClubs: "Klubovi",
  strNationality: "Nacionalnost",
  strLogin: "Prijava",
  strUserName: "Korisničko ime",
  strPassword: "Lozinka",
  strWrongInput: "Pogrešno korisničko ime ili lozinka",
  strCreateProfile: "Kreiraj novi profil",
  strWrongPassword: "Password doesn't match",
  strSuccessfulyRegistration: "Uspješna registracija",
  strError: "Dogodila se pogreška",
  strWrongEmail: "Email nije validan",
  strAlreadyInUseEmail: "Ovaj email se već koristi",
  strRequired: "Obvezno",
  strAlreadyInUseUserName: "Ovo korisničko ime se već koristi",
  strValidPaswword: "Ispravna lozinka",
  strPasswordLenght: "Lozinka mora imati barem 6 znakova",
  strConfirmPassword: "Potvrdi lozinku",
  strRepeatedPasswordNotValid: "Ponovljena lozinka nije validna",
  strRegister: "Registiraj se",
  strComment: "Komentiraj",
  strAddComment: "Dodaj komentar",
  strCancel: "Odustani",
  strConfirm: "Potvrdi",
  strScoreHome: "Rezultat domaćin",
  strScoreAway: "Rezultat gost",
  strCommentDeleteConfirmation: "Jeste li sigurni da želite obrisati komentar?",
  strDeleteConfirmation: "Jeste li sigurni da želite  ",
  strYes: "Da",
  strNo: "Ne",
  strEdit: "Uređivanje",
  strLogout: "Odjava",
  strRowsPerPage: "Broj redaka po stranici",
  strDeleting: "obrisati",
  strReturning: "vratiti",
  strDelete: "Obriši",
  strReturn: "Vrati",
  strSomethingWentWrong: "Nešto je pošlo po zlu",
  strSuccessfulyCreated: "Uspješno kreirano!",
  strSuccessfulyUpdated: "Uspješno ažurirano!",
  strSuccessfulyDeleted: "Uspješno obrisano!",
  strAlreadyTaken: " je zauzeto.",
  strPlayer: "Igrač",
  strPlayers: "Igrači",
  strChange: "Izmijeni",
  strScores: "Rezultati",
  strSchedule: "Raspored",
  strFavourites: "Favoriti",
  strBack: "Natrag",
  strNoResults: "Nema rezultata",
  strNoClubs: "Nema klubova",
  strNoLeagues: "Nema liga",
  strSearchPlaceholder: "Upišite traženi pojam",
  strSearchClubsAndLeagues: "Pretraži klubove i lige",
  strErrorBirthDate: "Datum rođenja nije ispravan",
};

export const stringDe = {
  strName: "Name",
  strLogo: "Logo",
  strLeague: "Liga",
  strLeagues: "Ligen",
  strLocation: "Ort",
  strCountry: "Land",
  strSport: "Sport",
  strAddress: "Adresse",
  strTime: "Zeit",
  strHome: "Zuhause",
  strAway: "Gast",
  strAll: "Alle",
  strFinished: "Beendet",
  strNotFinished: "Nicht beendet",
  strOrderBy: "Sortiere nach:",
  strMatch: "Spiel",
  strAsc: "Aufsteigende Reihenfolge",
  strShowDeleted: "Gelöschte anzeigen",
  strScore: "2Ergebnis",
  strAdd: "Hinzufügen",
  strSearch: "Suche:",
  strSearchWithoutSemicolon: "Suche",
  strFirstName: "Vorname",
  strLastName: "Nachname",
  strImage: "Bild",
  strBirthDate: "Geburtsdatum",
  strClub: "Verein",
  strClubs: "Vereine",
  strNationality: "Nationalität",
  strLogin: "Anmeldung",
  strUserName: "Benutzername",
  strPassword: "Passwort",
  strWrongInput: "Falscher Benutzername oder Passwort",
  strCreateProfile: "Neues Profil erstellen",
  strWrongPassword: "Passwort stimmt nicht überein",
  strSuccessfulyRegistration: "Erfolgreiche Registrierung",
  strError: "Ein Fehler ist aufgetreten",
  strWrongEmail: "E-Mail ist ungültig",
  strAlreadyInUseEmail: "Diese E-Mail wird bereits verwendet",
  strRequired: "Erforderlich",
  strAlreadyInUseUserName: "Dieser Benutzername wird bereits verwendet",
  strValidPaswword: "Gültiges Passwort",
  strPasswordLenght: "Passwort muss mindestens 6 Zeichen lang sein",
  strConfirmPassword: "Passwort bestätigen",
  strRepeatedPasswordNotValid: "Wiederholtes Passwort ist ungültig",
  strRegister: "Registrieren",
  strComment: "Kommentar",
  strAddComment: "Kommentar hinzufügen",
  strCancel: "Stornieren",
  strConfirm: "Bestätigen",
  strScoreHome: "Heim Ergebnis",
  strScoreAway: "Auswärts Ergebnis",
  strCommentDeleteConfirmation:
    "Sind Sie sicher, dass Sie den Kommentar löschen möchten?",
  strDeleteConfirmation: "Sind Sie sicher, dass Sie ",
  strYes: "Ja",
  strNo: "Nein",
  strEdit: "Bearbeiten",
  strLogout: "Abmelden",
  strRowsPerPage: "Anzahl der Zeilen pro Seite",
  strDeleting: "löschen",
  strReturning: "zurückkehren",
  strDelete: "Löschen",
  strReturn: "Zurück",
  strSomethingWentWrong: "Etwas ist schief gelaufen",
  strSuccessfulyCreated: "Erfolgreich erstellt!",
  strSuccessfulyUpdated: "Erfolgreich aktualisiert!",
  strSuccessfulyDeleted: "Erfolgreich gelöscht!",
  strAlreadyTaken: " ist bereits vergeben.",
  strPlayer: "Spieler",
  strPlayers: "Spieler",
  strChange: "Ändern",
  strScores: "Ergebnisse",
  strSchedule: "Spielplan",
  strFavourites: "Favoriten",
  strBack: "Zurück",
  strNoResults: "Keine Ergebnisse",
  strNoClubs: "Keine Vereine",
  strNoLeagues: "Keine Ligen",
  strSearchPlaceholder: "Geben Sie einen Suchbegriff ein",
  strSearchClubsAndLeagues: "Vereine und Ligen durchsuchen",
  strErrorBirthDate: "Geburtsdatum ist ungültig",
};

export const stringFr = {
  strName: "Nom",
  strLogo: "Logo",
  strLeague: "Ligue",
  strLeagues: "Ligues",
  strLocation: "Emplacement",
  strCountry: "Pays",
  strSport: "Sport",
  strAddress: "Adresse",
  strTime: "Heure",
  strHome: "Domicile",
  strAway: "Extérieur",
  strAll: "Tous",
  strFinished: "Terminées",
  strNotFinished: "Non terminées",
  strOrderBy: "Trier par:",
  strMatch: "Matchs",
  strAsc: "Ordre croissant",
  strShowDeleted: "Afficher les supprimés",
  strScore: "2Score",
  strAdd: "Ajouter",
  strSearch: "Rechercher:",
  strSearchWithoutSemicolon: "Rechercher",
  strFirstName: "Prénom",
  strLastName: "Nom de famille",
  strImage: "Image",
  strBirthDate: "Date de naissance",
  strClub: "Club",
  strClubs: "Clubs",
  strNationality: "Nationalité",
  strLogin: "Connexion",
  strUserName: "Nom d'utilisateur",
  strPassword: "Mot de passe",
  strWrongInput: "Nom d'utilisateur ou mot de passe incorrect",
  strCreateProfile: "Créer un nouveau profil",
  strWrongPassword: "Le mot de passe ne correspond pas",
  strSuccessfulyRegistration: "Inscription réussie",
  strError: "Une erreur est survenue",
  strWrongEmail: "L'e-mail n'est pas valide",
  strAlreadyInUseEmail: "Cet e-mail est déjà utilisé",
  strRequired: "Requis",
  strAlreadyInUseUserName: "Ce nom d'utilisateur est déjà utilisé",
  strValidPaswword: "Mot de passe valide",
  strPasswordLenght: "Le mot de passe doit contenir au moins 6 caractères",
  strConfirmPassword: "Confirmez le mot de passe",
  strRepeatedPasswordNotValid: "Le mot de passe répété n'est pas valide",
  strRegister: "S'inscrire",
  strComment: "Commentaire",
  strAddComment: "Ajouter un commentaire",
  strCancel: "Annuler",
  strConfirm: "Confirmer",
  strScoreHome: "Résultat à domicile",
  strScoreAway: "Résultat à l'extérieur",
  strCommentDeleteConfirmation:
    "Êtes-vous sûr de vouloir supprimer le commentaire?",
  strDeleteConfirmation: "Êtes-vous sûr de vouloir supprimer ",
  strYes: "Oui",
  strNo: "Non",
  strEdit: "Modifier",
  strLogout: "Se déconnecter",
  strRowsPerPage: "Nombre de lignes par page",
  strDeleting: "supprimer",
  strReturning: "retourner",
  strDelete: "Supprimer",
  strReturn: "Retour",
  strSomethingWentWrong: "Quelque chose s'est mal passé",
  strSuccessfulyCreated: "Création réussie!",
  strSuccessfulyUpdated: "Mise à jour réussie!",
  strSuccessfulyDeleted: "Suppression réussie!",
  strAlreadyTaken: " est déjà pris.",
  strPlayer: "Joueur",
  strPlayers: "Joueurs",
  strChange: "Modifier",
  strScores: "Scores",
  strSchedule: "Calendrier",
  strFavourites: "Favoris",
  strBack: "Retour",
  strNoResults: "Aucun résultat",
  strNoClubs: "Aucun club",
  strNoLeagues: "Aucune ligue",
  strSearchPlaceholder: "Entrez un terme de recherche",
  strSearchClubsAndLeagues: "Rechercher des clubs et des ligues",
  strErrorBirthDate: "La date de naissance n'est pas valide",
};

export const stringEs = {
  strName: "Nombre",
  strLogo: "Logo",
  strLeague: "Liga",
  strLeagues: "Ligas",
  strLocation: "Ubicación",
  strCountry: "País",
  strSport: "Deporte",
  strAddress: "Dirección",
  strTime: "Hora",
  strHome: "Local",
  strAway: "Visitante",
  strAll: "Todo",
  strFinished: "Finalizadas",
  strNotFinished: "No finalizadas",
  strOrderBy: "Ordenar por:",
  strMatch: "Partidos",
  strAsc: "Orden ascendente",
  strShowDeleted: "Mostrar eliminados",
  strScore: "2Resultado",
  strAdd: "Agregar",
  strSearch: "Buscar:",
  strSearchWithoutSemicolon: "Buscar",
  strFirstName: "Nombre",
  strLastName: "Apellido",
  strImage: "Imagen",
  strBirthDate: "Fecha de nacimiento",
  strClub: "Club",
  strClubs: "Clubes",
  strNationality: "Nacionalidad",
  strLogin: "Iniciar sesión",
  strUserName: "Nombre de usuario",
  strPassword: "Contraseña",
  strWrongInput: "Nombre de usuario o contraseña incorrectos",
  strCreateProfile: "Crear nuevo perfil",
  strWrongPassword: "La contraseña no coincide",
  strSuccessfulyRegistration: "Registro exitoso",
  strError: "Ha ocurrido un error",
  strWrongEmail: "El correo electrónico no es válido",
  strAlreadyInUseEmail: "Este correo electrónico ya está en uso",
  strRequired: "Requerido",
  strAlreadyInUseUserName: "Este nombre de usuario ya está en uso",
  strValidPaswword: "Contraseña válida",
  strPasswordLenght: "La contraseña debe tener al menos 6 caracteres",
  strConfirmPassword: "Confirmar contraseña",
  strRepeatedPasswordNotValid: "La contraseña repetida no es válida",
  strRegister: "Registrarse",
  strComment: "Comentario",
  strAddComment: "Agregar comentario",
  strCancel: "Cancelar",
  strConfirm: "Confirmar",
  strScoreHome: "Resultado local",
  strScoreAway: "Resultado visitante",
  strCommentDeleteConfirmation:
    "¿Estás seguro de que quieres eliminar el comentario?",
  strDeleteConfirmation: "¿Estás seguro de que quieres ",
  strYes: "Sí",
  strNo: "No",
  strEdit: "Editar",
  strLogout: "Cerrar sesión",
  strRowsPerPage: "Número de filas por página",
  strDeleting: "eliminar",
  strReturning: "regresar",
  strDelete: "Eliminar",
  strReturn: "Volver",
  strSomethingWentWrong: "Algo salió mal",
  strSuccessfulyCreated: "¡Creado exitosamente!",
  strSuccessfulyUpdated: "¡Actualizado exitosamente!",
  strSuccessfulyDeleted: "¡Eliminado exitosamente!",
  strAlreadyTaken: " ya está en uso.",
  strPlayer: "Jugador",
  strPlayers: "Jugadores",
  strChange: "Cambiar",
  strScores: "Resultados",
  strSchedule: "Calendario",
  strFavourites: "Favoritos",
  strBack: "Volver",
  strNoResults: "Sin resultados",
  strNoClubs: "Sin clubes",
  strNoLeagues: "Sin ligas",
  strSearchPlaceholder: "Ingrese un término de búsqueda",
  strSearchClubsAndLeagues: "Buscar clubes y ligas",
  strErrorBirthDate: "La fecha de nacimiento no es válida",
};

export const stringSv = {
  strName: "Namn",
  strLogo: "Logo",
  strLeague: "Liga",
  strLeagues: "Ligor",
  strLocation: "Plats",
  strCountry: "Land",
  strSport: "Sport",
  strAddress: "Adress",
  strTime: "Tid",
  strHome: "Hemmalag",
  strAway: "Bortalag",
  strAll: "Alla",
  strFinished: "Avslutade",
  strNotFinished: "Ej avslutade",
  strOrderBy: "Sortera efter:",
  strMatch: "Matcher",
  strAsc: "Stigande ordning",
  strShowDeleted: "Visa raderade",
  strScore: "2Resultat",
  strAdd: "Lägg till",
  strSearch: "Sök:",
  strSearchWithoutSemicolon: "Sök",
  strFirstName: "Förnamn",
  strLastName: "Efternamn",
  strImage: "Bild",
  strBirthDate: "Födelsedatum",
  strClub: "Klubb",
  strClubs: "Klubbar",
  strNationality: "Nationalitet",
  strLogin: "Logga in",
  strUserName: "Användarnamn",
  strPassword: "Lösenord",
  strWrongInput: "Felaktigt användarnamn eller lösenord",
  strCreateProfile: "Skapa nytt profil",
  strWrongPassword: "Lösenorden matchar inte",
  strSuccessfulyRegistration: "Lyckad registrering",
  strError: "Ett fel har inträffat",
  strWrongEmail: "E-postadressen är ogiltig",
  strAlreadyInUseEmail: "Denna e-postadress används redan",
  strRequired: "Obligatoriskt",
  strAlreadyInUseUserName: "Detta användarnamn används redan",
  strValidPaswword: "Giltigt lösenord",
  strPasswordLenght: "Lösenordet måste vara minst 6 tecken långt",
  strConfirmPassword: "Bekräfta lösenord",
  strRepeatedPasswordNotValid: "Det upprepade lösenordet är ogiltigt",
  strRegister: "Registrera",
  strComment: "Kommentar",
  strAddComment: "Lägg till kommentar",
  strCancel: "Avbryt",
  strConfirm: "Bekräfta",
  strScoreHome: "Hemmamatchens resultat",
  strScoreAway: "Bortamatchens resultat",
  strCommentDeleteConfirmation:
    "Är du säker på att du vill radera kommentaren?",
  strDeleteConfirmation: "Är du säker på att du vill radera ",
  strYes: "Ja",
  strNo: "Nej",
  strEdit: "Redigera",
  strLogout: "Logga ut",
  strRowsPerPage: "Antal rader per sida",
  strDeleting: "radera",
  strReturning: "återvända",
  strDelete: "Radera",
  strReturn: "Tillbaka",
  strSomethingWentWrong: "Något gick fel",
  strSuccessfulyCreated: "Skapat framgångsrikt!",
  strSuccessfulyUpdated: "Uppdaterat framgångsrikt!",
  strSuccessfulyDeleted: "Raderat framgångsrikt!",
  strAlreadyTaken: " är redan upptaget.",
  strPlayer: "Spelare",
  strPlayers: "Spelare",
  strChange: "Ändra",
  strScores: "Resultat",
  strSchedule: "Schema",
  strFavourites: "Favoriter",
  strBack: "Tillbaka",
  strNoResults: "Inga resultat",
  strNoClubs: "Inga klubbar",
  strNoLeagues: "Inga ligor",
  strSearchPlaceholder: "Skriv in sökterm",
  strSearchClubsAndLeagues: "Sök klubbar och ligor",
  strErrorBirthDate: "Födelsedatumet är ogiltigt",
};
