export const stringEn = {
  strName: "Name",
  strLogo: "Logo",
  strLeague: "League",
  strLocation: "Location",
  strCountry: "Country",
  strSport: "Sport",
  strAddress: "Address",
  strTime: "Time",
  strHome: "Home",
  strAway: "Away",
  strAll: "All",
  strFinished: "Finished",
  strNotFinished: "Not Finished",
  strOrderBy: "Order by:",
  strMatch: "Matches:",
  strAsc: "Ascending order",
  strShowDeleted: "Show deleted",
  strScore: "Score",
  strAdd: "Add",
  strSearch: "Search:",
  strFirstName: "First Name",
  strLastName: "Last Name",
  strImage: "Image",
  strBirthDate: "Birth Date",
  strClub: "Club",
  strNationality: "Nationality",
  strLogin: "Login",
  strUserName: "Username",
  strPassword: "Password",
  strWrongInput: "Wrong username or password",
  strCreateProfile: "Create new profile",
  strWrongPassword: "Password doesn't match",
  strSuccessfulyRegistration: "Successful registration",
  strError: "An error occurred",
  strWrongEmail: "Email is not valid",
  strAlreadyInUseEmail: "This email is already in use",
  strRequired: "Required",
  strAlreadyInUseUserName: "This username is already in use",
  strValidPaswword: "Valid password",
  strPasswordLenght: "Password must be at least 6 characters long",
  strConfirmPassword: "Confirm password",
  strRepeatedPasswordNotValid: "Repeated password is not valid",
  strRegister: "Register",
  strComment: "Comment",
  strAddComment: "Add comment",
  strConfirm: "Confirm",
  strScoreHome: "Home score",
  strScoreAway: "Away score",
  strCommentDeleteConfirmation: "Are you sure you want to delete the comment?",
  strDeleteConfirmation: "Are you sure you want to delete ",
  strYes: "Yes",
  strNo: "No",
  strEdit: "Edit",
  strLogout: "Logout",
  strRowsPerPage: "Rows per page",
  strDelete: "Delete",
  strReturn: "Return",
  strSomethingWentWrong: "Something went wrong",
  strSuccessfulyCreated: "Successfully created!",
  strSuccessfulyUpdated: "Successfully updated!",
  strSuccessfulyDeleted: "Successfully deleted!",
  strAlreadyTaken: " is already taken.",
  strPlayer: "Player",
  strChange: "Edit",
};

export const stringHr = {
  strName: "Naziv",
  strLogo: "Logo",
  strLeague: "Liga",
  strLocation: "Lokacija",
  strCountry: "Država",
  strSport: "Sport",
  strAddress: "Adresa",
  strTime: "Vrijeme",
  strHome: "Domaćin",
  strAway: "Gost",
  strAll: "Sve",
  strFinished: "Završene",
  strNotFinished: "Nisu Završene",
  strOrderBy: "Poredaj po:",
  strMatch: "Utakmice:",
  strAsc: "Rastući redoslijed",
  strShowDeleted: "Prikaži izbrisane",
  strScore: "2Rezultat",
  strAdd: "Dodaj",
  strSearch: "Pretraži:",
  strFirstName: "Ime",
  strLastName: "Prezime",
  strImage: "Slika",
  strBirthDate: "Datum rođenja",
  strClub: "Klub",
  strNationality: "Nacionalnost",
  strLogin: "Prijava",
  strUserName: "Korisničko ime",
  strPassword: "Lozinka",
  strWrongInput: "Pogrešno korisničko ime ili lozinka",
  strCreateProfile: "Kreiraj novi profil",
  strWrongPassword: "Password doesn't match",
  strSuccessfulyRegistration: "Uspješna registracija",
  strError: "Dogodila se pogreška",
  strWrongEmail: "Email nije validan",
  strAlreadyInUseEmail: "Ovaj email se već koristi",
  strRequired: "Obvezno",
  strAlreadyInUseUserName: "Ovo korisničko ime se već koristi",
  strValidPaswword: "Ispravna lozinka",
  strPasswordLenght: "Lozinka mora imati barem 6 znakova",
  strConfirmPassword: "Potvrdi lozinku",
  strRepeatedPasswordNotValid: "Ponovljena lozinka nije validna",
  strRegister: "Registiraj se",
  strComment: "Komentiraj",
  strAddComment: "Dodaj komentar",
  strConfirm: "Potvrdi",
  strScoreHome: "Rezultat domaćin",
  strScoreAway: "Rezultat gost",
  strCommentDeleteConfirmation: "Jeste li sigurni da želite obrisati komentar?",
  strDeleteConfirmation: "Jeste li sigurni da želite obrisati ",
  strYes: "Da",
  strNo: "Ne",
  strEdit: "Uređivanje",
  strLogout: "Odjava",
  strRowsPerPage: "Broj redaka po stranici",
  strDelete: "Obriši",
  strReturn: "Vrati",
  strSomethingWentWrong: "Nešto je pošlo po zlu",
  strSuccessfulyCreated: "Uspješno kreirano!",
  strSuccessfulyUpdated: "Uspješno ažurirano!",
  strSuccessfulyDeleted: "Uspješno obrisano!",
  strAlreadyTaken: " je zauzeto.",
  strPlayer: "Igrač",
  strChange: "Izmijeni",
};
