// <auto-generated />
namespace ResultApp.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class jfxdjxdzj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jfxdjxdzj));
        
        string IMigrationMetadata.Id
        {
            get { return "202307150903143_jfxdjxdzj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
